name: Maven Publish

on:
#  push:
#    tags:
#      - "v*.*.*"
  release:
    types: [ published ]

env:
  MAVEN_DEPLOY_PASSWORD: ${{ secrets.MAVEN_DEPLOY_PASSWORD }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '8'
            cache: 'maven'
            server-id: oss # Value of the distributionManagement/repository/id field of the pom.xml
            settings-path: ${{ github.workspace }} # location for the settings.xml file
        - uses: actions/checkout@v3
        - run: |
            env
  